# Generated by Django 5.2.17 on 2026-09-03 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Tên địa danh')),
                ('full_name', models.CharField(max_length=255, verbose_name='Tên đầy đủ')),
                ('latitude', models.FloatField(verbose_name='Vĩ độ')),
                ('longitude', models.FloatField(verbose_name='Kinh độ')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Quốc gia')),
                ('country_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Mã quốc gia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Địa điểm',
                'verbose_name_plural': 'Danh sách địa điểm',
                'unique_together': {('latitude', 'longitude')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='anonymous', max_length=100, verbose_name='ID người dùng')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='weather_app.location')),
            ],
            options={
                'verbose_name': 'Địa điểm yêu thích',
                'verbose_name_plural': 'Danh sách yêu thích',
            },
        ),
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(db_index=True)),
                ('longitude', models.FloatField(db_index=True)),
                ('place_name', models.CharField(max_length=255)),
                ('temperature', models.FloatField(verbose_name='Nhiệt độ hiện tại')),
                ('feels_like', models.FloatField(verbose_name='Nhiệt độ cảm nhận')),
                ('humidity', models.IntegerField(verbose_name='Độ ẩm (%)')),
                ('wind_speed', models.FloatField(verbose_name='Tốc độ gió (km/h)')),
                ('wind_direction', models.FloatField(default=0, verbose_name='Hướng gió')),
                ('weather_code', models.IntegerField(verbose_name='Mã WMO')),
                ('description', models.CharField(max_length=150, verbose_name='Mô tả thời tiết')),
                ('uv_index', models.FloatField(default=0, verbose_name='Chỉ số UV')),
                ('pressure', models.FloatField(default=1013, verbose_name='Áp suất (hPa)')),
                ('precipitation', models.FloatField(default=0, verbose_name='Lượng mưa (mm)')),
                ('raw_payload', models.JSONField(verbose_name='Dữ liệu JSON thô đầy đủ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lúc')),
            ],
            options={
                'verbose_name': 'Bộ đệm Thời tiết',
                'verbose_name_plural': 'Bộ đệm Thời tiết',
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='weather_app_latitud_c7515e_idx')],
            },
        ),
    ]
